### ISSUE TITLE
geckodriver.exe

### ISSUE THREAD

**Issue by tomg404** [shubham-735/Top-Insta-Post-Downloader#3]
```
Traceback (most recent call last):
  File "D:\Users\Tom\anaconda3\envs\trash\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "D:\Users\Tom\anaconda3\envs\trash\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Users\Tom\anaconda3\envs\trash\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insta.py", line 8, in <module>
    driver = webdriver.Firefox(executable_path='C:\\Users\shubh\Desktop\geckodriver.exe')
  File "D:\Users\Tom\anaconda3\envs\trash\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "D:\Users\Tom\anaconda3\envs\trash\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver.exe' executable needs to be in PATH.
```
Error when running `insta.py`.
Maybe consider adding the geckodriver to your repository.

**Comment by shubh-am-735** [comment]
Error is resolved as geckodriver added to support Windows and Linux compatability
